spring.application.name=campushire-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/campushiredb
spring.datasource.username=postgres
spring.datasource.password=root123
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration,org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=campushire90@gmail.com
spring.mail.password=qxse donf ctho aeoz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
